steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - >-
        us-central1-docker.pkg.dev/jha-project-489805/demo-api-artifact/demoapi:v1
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        us-central1-docker.pkg.dev/jha-project-489805/demo-api-artifact/demoapi:v1
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - deploy
      - weatherapi-service
      - '--image'
      - >-
        us-central1-docker.pkg.dev/jha-project-489805/demo-api-artifact/demoapi:v1
      - '--region'
      - us-central1
      - '--platform'
      - managed
      - '--allow-unauthenticated'
    entrypoint: gcloud
images:
  - us-central1-docker.pkg.dev/jha-project-489805/demo-api-artifact/demoapi:v1
options:
  logging: CLOUD_LOGGING_ONLY
